### ISSUE TITLE
cmds.yml bug

### ISSUE THREAD

**Issue by sorandno** [ArVdC/TimeManager#29]
cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-15'
    repeatFreq: month

This setting did not work.
It seems there is still a bug.

**Comment by sorandno** [comment]
It may not work depending on the time, so I will test this setting tomorrow to see if it works.

  '1':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:59'
    date: '2024-06-17'
    repeatFreq: month
  '2':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:59'
    date: '2024-06-17'
    repeatFreq: month
  '3':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-17'
    repeatFreq: month
  '4':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:59'
    date: '2024-06-17'
    repeatFreq: month
  '5':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:00'
    date: '2024-06-17'
    repeatFreq: month
  '6':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:00'
    date: '2024-06-17'
    repeatFreq: month
  '7':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:00'
    date: '2024-06-17'
    repeatFreq: month
  '8':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:00'
    date: '2024-06-17'
    repeatFreq: month
  '9':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '13:00'
    date: '2024-06-17'
    repeatFreq: month

**Comment by sorandno** [comment]
version: 1.9.1-b
useCmds: 'true'
cmdsList:
  '1':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:59'
    date: '2024-06-17'
    repeatFreq: month
  '2':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:59'
    date: '2024-06-17'
    repeatFreq: month
  '3':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-17'
    repeatFreq: month
  '4':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:59'
    date: '2024-06-17'
    repeatFreq: month
  '5':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:00'
    date: '2024-06-17'
    repeatFreq: month
  '6':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:00'
    date: '2024-06-17'
    repeatFreq: month
  '7':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:00'
    date: '2024-06-17'
    repeatFreq: month
  '8':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:00'
    date: '2024-06-17'
    repeatFreq: month
  '9':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '13:00'
    date: '2024-06-17'
    repeatFreq: month

It may not work depending on the time, so I will test this setting tomorrow to see if it works.

**Comment by sorandno** [comment]
It may not work depending on the time, so I will test this setting tomorrow to see if it works.
```
version: 1.9.1-b
useCmds: 'true'
cmdsList:
  '1':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:59'
    date: '2024-06-17'
    repeatFreq: month
  '2':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:59'
    date: '2024-06-17'
    repeatFreq: month
  '3':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-17'
    repeatFreq: month
  '4':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:59'
    date: '2024-06-17'
    repeatFreq: month
  '5':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:00'
    date: '2024-06-17'
    repeatFreq: month
  '6':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:00'
    date: '2024-06-17'
    repeatFreq: month
  '7':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:00'
    date: '2024-06-17'
    repeatFreq: month
  '8':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:00'
    date: '2024-06-17'
    repeatFreq: month
  '9':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '13:00'
    date: '2024-06-17'
    repeatFreq: month

```

**Comment by sorandno** [comment]
The following didn't work.
```
  '1':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:59'
    date: '2024-06-17'
    repeatFreq: month
  '2':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:59'
    date: '2024-06-17'
    repeatFreq: month
  '3':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-17'
    repeatFreq: month
  '4':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:59'
    date: '2024-06-17'
    repeatFreq: month
```

**Comment by ArVdC** [comment]
I've tried all of this and it seems to work.
Are you sure there isn't another possible cause?

**Comment by sorandno** [comment]
It seems that 59 minutes cannot be used in my environment.

The 50 minute mark is working...

**Comment by sorandno** [comment]
Is it not executed in Japanese time?

**Comment by ArVdC** [comment]
Maybe try using '/tm set devmode true' in the console to see more details about the process.

**Comment by sorandno** [comment]
how is it?

cmds.yml
```
version: 1.9.1-b
useCmds: 'true'
cmdsList:
  '1':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '9:59'
    date: '2024-06-22'
    repeatFreq: month
  '2':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '10:59'
    date: '2024-06-22'
    repeatFreq: month
  '3':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-22'
    repeatFreq: month
  '4':
    cmds:
      '1': test
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '12:59'
    date: '2024-06-22'
    repeatFreq: month

```

LOG
```
[12:20:00 INFO]: [TimeManager] Command #1
[12:20:00 INFO]: [TimeManager] Current UTC Date and Time : 2024-06-21T12:20
[12:20:00 INFO]: [TimeManager] Expected Date and Time :    2024-06-22T09:59
[12:20:00 INFO]: [TimeManager] Edge Date and Time :        2024-06-22T10:00
[12:20:00 INFO]: [TimeManager] Interval : 1 minutes (#1200)
[12:20:00 INFO]: [TimeManager] Reference Time Source : UTC+9
[12:20:00 INFO]: [TimeManager] Repeat Frequence : month
[12:20:00 INFO]: [TimeManager] ==================
[12:20:00 INFO]: [TimeManager] Days will now be checked :
[12:20:00 INFO]: [TimeManager] The data of the day does not correspond, do nothing.
[12:20:00 INFO]: [TimeManager] Command #2
[12:20:00 INFO]: [TimeManager] Current UTC Date and Time : 2024-06-21T12:20
[12:20:00 INFO]: [TimeManager] Expected Date and Time :    2024-06-22T10:59
[12:20:00 INFO]: [TimeManager] Edge Date and Time :        2024-06-22T11:00
[12:20:00 INFO]: [TimeManager] Interval : 1 minutes (#1200)
[12:20:00 INFO]: [TimeManager] Reference Time Source : UTC+9
[12:20:00 INFO]: [TimeManager] Repeat Frequence : month
[12:20:00 INFO]: [TimeManager] ==================
[12:20:00 INFO]: [TimeManager] Days will now be checked :
[12:20:00 INFO]: [TimeManager] The data of the day does not correspond, do nothing.
[12:20:00 INFO]: [TimeManager] Command #3
[12:20:00 INFO]: [TimeManager] Current UTC Date and Time : 2024-06-21T12:20
[12:20:00 INFO]: [TimeManager] Expected Date and Time :    2024-06-22T11:59
[12:20:00 INFO]: [TimeManager] Edge Date and Time :        2024-06-22T12:00
[12:20:00 INFO]: [TimeManager] Interval : 1 minutes (#1200)
[12:20:00 INFO]: [TimeManager] Reference Time Source : UTC+9
[12:20:00 INFO]: [TimeManager] Repeat Frequence : month
[12:20:00 INFO]: [TimeManager] ==================
[12:20:00 INFO]: [TimeManager] Days will now be checked :
[12:20:00 INFO]: [TimeManager] The data of the day does not correspond, do nothing.
[12:20:00 INFO]: [TimeManager] Command #4
[12:20:00 INFO]: [TimeManager] Current UTC Date and Time : 2024-06-21T12:20
[12:20:00 INFO]: [TimeManager] Expected Date and Time :    2024-06-22T12:59
[12:20:00 INFO]: [TimeManager] Edge Date and Time :        2024-06-22T13:00
[12:20:00 INFO]: [TimeManager] Interval : 1 minutes (#1200)
[12:20:00 INFO]: [TimeManager] Reference Time Source : UTC+9
[12:20:00 INFO]: [TimeManager] Repeat Frequence : month
[12:20:00 INFO]: [TimeManager] ==================
[12:20:00 INFO]: [TimeManager] Days will now be checked :
[12:20:00 INFO]: [TimeManager] The data of the day does not correspond, do nothing.
```

**Comment by ArVdC** [comment]
I meant between hh:58 and hh:00

**Comment by sorandno** [comment]
After all, it doesn't move at 59 minutes.
It worked for 50 minutes.

**Comment by ArVdC** [comment]
`The data of the day does not correspond, do nothing.`
Don't forget to change the expected date in the yml file, or set `Repeat Frequence : month` to `Repeat Frequence : day`

**Comment by sorandno** [comment]
No, I set it up the day before and checked it the next day and it didn't work.

**Comment by sorandno** [comment]
This problem may be fixed.

[TimeManager v1.10.1](https://github.com/ArVdC/TimeManager/releases/tag/v1.10.1) worked in units other than 10 minutes.

I will test and report whether it works at 4:59, which previously did not work.

However, the version currently being tested is 1.21.

**Comment by ArVdC** [comment]
Please re-download, I quickly tested the changes and I think it works for all hours and minutes.

**Comment by sorandno** [comment]
I got it.
Test again.

**Comment by sorandno** [comment]
It didn't move.
The tested settings are below.

````
  '2':
    cmds:
      '1': /restart1
    cmdsRefTime: UTC+9
    plholderRefWorld: life
    time: '4:59'
    date: '2024-11-18'
    repeatFreq: day
````
