### ISSUE TITLE
Feature request : / symbol not accepted.

### ISSUE THREAD

**Issue by Pro245Mc** [ArVdC/TimeManager#31]
Hi,
In the plugin, is it possible to use the / symbol in the cms.yml? I use a plugin that looks for music files in folders, but I can't add the /.

Example: 
      '4': /oa region create __global__ ["files:public/home/77night01.mp3"]

This part is not recognised : public/home/
Thanks

**Comment by ArVdC** [comment]
I think I know why, I'll check it asap

**Comment by Pro245Mc** [comment]
Hi there,
Sorry to be a bother. Just wanted to know approximated how long before this could be fixed?

**Comment by ArVdC** [comment]
Here it is : [ https://github.com/ArVdC/TimeManager/releases/tag/v1.9.1-b2](https://github.com/ArVdC/TimeManager/releases/tag/v1.9.1-b2)

**Comment by Pro245Mc** [comment]
Thank you so much for this. Means a lot. Take care

**Comment by Pro245Mc** [comment]
Hi again.
Ok so i've tested it. The (/ ) Works good, but it seems to have broken my conf. I reverted to the old update (1.9.0) and it works again. 
This is kind of related the the day cycles request, so i will add my conf so you can see what isn't working in your new update , as i know it's a beta pre release.

So the bug with 1.9.1 pre-release is: 
In my cmd.yml, the days seem to all skip though one another. But in 1.9.0 it works. As if it no longer respects the dates.
I managed to concoct a weekly days cycle. It was I bit annoying to configure, but the trick was to create a 8th day on sunday night.)
Maybe it could inspire your coding for the new feature? haha. (you guys are amazing at coding by the way. I know very little, but i love this plugin)

anyway, here's my yml. Thanks so much for your time.

```
version: 1.9.0
useCmds: 'true'
cmdsList:
  global_day_music_day_01:
    cmds:
      '1': /broadcast &e&o[Monday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-01'
    repeatFreq: none
  global_day_music_day_02:
    cmds:
      '1': /broadcast &e&o[Tuesday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-02'
    repeatFreq: none
  global_day_music_day_03:
    cmds:
      '1': /broadcast &e&o[Wednesday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-03'
    repeatFreq: none
  global_day_music_day_04:
    cmds:
      '1': /broadcast &e&o[Thurday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-04'
    repeatFreq: none
  global_day_music_day_05:
    cmds:
      '1': /broadcast &e&o[Friday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-05'
    repeatFreq: none
  global_day_music_day_06:
    cmds:
      '1': /broadcast &e&o[Saturday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-06'
    repeatFreq: none
  global_day_music_day_07:
    cmds:
      '1': /broadcast &e&o[Sunday]
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:19
    date: '0001-01-07'
    repeatFreq: none
  global_night_music_night_01:
    cmds:
      '1': /broadcast &9&o[Sunday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-08'
    repeatFreq: none
  global_night_music_night_02:
    cmds:
      '1': /broadcast &9&o[Monday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-02'
    repeatFreq: none
  global_night_music_night_03:
    cmds:
      '1': /broadcast &9&o[Tuesday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-03'
    repeatFreq: none
  global_night_music_night_04:
    cmds:
      '1': /broadcast &9&o[Wednesday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-04'
    repeatFreq: none
  global_night_music_night_05:
    cmds:
      '1': /broadcast &9&o[Thursday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-05'
    repeatFreq: none
  global_night_music_night_06:
    cmds:
      '1': /broadcast &9&o[Friday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-06'
    repeatFreq: none
  global_night_music_night_07:
    cmds:
      '1': /broadcast &9&o[Saturday Night]
    cmdsRefTime: world
    plholderRefWorld: world
    time: '19:08'
    date: '0001-01-07'
    repeatFreq: none
  date_reset_monday_next_day:
    cmds:
      '1': /tm set date 0001-01-01 all
    cmdsRefTime: world
    plholderRefWorld: world
    time: 05:18
    date: '0001-01-08'
    repeatFreq: none

```
